nim js -r tests/test_arrays.nim || exit
nim js -r tests/test_char.nim || exit
nim js -r tests/test_enums.nim || exit
nim js -r tests/test_errors.nim || exit
nim js -r tests/test_fast_numbers.nim || exit
nim js -r tests/test_json_in_json.nim || exit
nim js -r tests/test_numbers.nim || exit
nim js -r tests/test_objects.nim || exit
nim js -r tests/test_options.nim || exit
nim js -r tests/test_parseHook.nim || exit
nim js -r tests/test_sets.nim || exit
nim js -r tests/test_strings.nim || exit
nim js -r tests/test_tables.nim || exit
nim js -r tests/test_tojson.nim || exit
nim js -r tests/test_tuples.nim || exit
